CREATE TABLE STUDENT(
USN VARCHAR(10) PRIMARY KEY,
STUDENT_NAME VARCHAR(20),
STUDENT_PHONE VARCHAR(10) CHECK(  LENGTH(STUDENT_PHONE)=10  ),
STUDENT_EMAIL VARCHAR(30) CHECK(STUDENT_EMAIL LIKE '%@gmail.com') ,
STUDENT_CITY VARCHAR(20),
STUDENT_DOB DATE CHECK( STUDENT_DOB BETWEEN TO_DATE('01-01-2000', 'DD-MM-YYYY') AND TO_DATE('01-01-2005', 'DD-MM-YYYY'))
);
DROP TABLE STUDENT;
--INSERT INTO STUDENT VALUES('4SF20CI002','ABHI',123,'A@GMAIL','CITY','01-02-2002')
INSERT INTO STUDENT VALUES('4SF20CI002','ABHI',123,'A@GMAIL','CITY',TO_DATE('01/05/2002',DD/MM/YYYY));

SELECT USN,STUDENT_NAME,STUDENT_PHONE,STUDENT_EMAIL,STUDENT_CITY,TO_CHAR(STUDENT_DOB,'dd/MM/yyyy') AS STUDENT_DOB FROM STUDENT;
SELECT * FROM STUDENT;  
DELETE FROM STUDENT;
DESC STUDENT; 

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='STUDENT';
SELECT CURRENT_DATE from DUAL ; --DUAL is dummy table
SELECT CURRENT_TIMESTAMP from DUAL ;

--1. display students name who are born in october;]
SELECT STUDENT_NAME FROM STUDENT WHERE ;

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH:MM PM') FROM DUAL;

--2. display students who are bron in 2003
--3. display students who are bron in MONDAY
--4. Display student name who are 21 years age

