CREATE TABLE STUDENT(
USN VARCHAR(10) PRIMARY KEY,
STUDENT_NAME VARCHAR(20),
STUDENT_PHONE VARCHAR(10) CHECK(  LENGTH(STUDENT_PHONE)=10  ),
STUDENT_EMAIL VARCHAR(30) CHECK(STUDENT_EMAIL LIKE '%@gmail.com') ,
STUDENT_CITY VARCHAR(20),
STUDENT_DOB DATE CHECK( STUDENT_DOB BETWEEN TO_DATE('01-01-2000', 'DD-MM-YYYY') AND TO_DATE('01-01-2005', 'DD-MM-YYYY'))
);
DROP TABLE STUDENT;
--INSERT INTO STUDENT VALUES('4SF20CI002','ABHI',123,'A@GMAIL','CITY','01-02-2002');
SELECT * FROM STUDENT;
SELECT TO_CHAR(STUDENT_DOB,'dd/MM/yyyy') FROM STUDENT;
DELETE FROM STUDENT;
desc student; 
commit;